name: AIOS application

on:
  push:
    branches: [ "aios_v0.2" ]
  pull_request:
    branches: [ "aios_v0.2" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: aios_v0.2  # 指定检出 aios_v0.2 分支
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Git Clone Action
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: agiresearch/Cerebrum
        path: Cerebrum
        
    - name: Install cerebrum special edition
      run: |
        python -m pip install -e Cerebrum/
        
    - name: Run AIOS kernel in background
      run: |
        bash runtime/launch_kernel.sh &>logs &
        sleep 10  # 等待 kernel 启动
        
    - name: Run the run-agent code
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}  # 使用 GitHub secrets
      run: |
        run-agent \
          --llm_name gemini-1.5-flash \
          --llm_backend google \
          --agent_name_or_path demo_author/demo_agent \
          --task "Tell me what is core idea of AIOS" \
          --aios_kernel_url http://localhost:8000
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: logs
        path: logs
